-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LLSSineReconstruction_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_s is
port (
    alpha_strm1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    alpha_strm1_full_n : IN STD_LOGIC;
    alpha_strm1_write : OUT STD_LOGIC;
    beta_strm2_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    beta_strm2_full_n : IN STD_LOGIC;
    beta_strm2_write : OUT STD_LOGIC;
    gamma_strm3_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    gamma_strm3_full_n : IN STD_LOGIC;
    gamma_strm3_write : OUT STD_LOGIC;
    n : IN STD_LOGIC_VECTOR (1 downto 0);
    col_i : IN STD_LOGIC_VECTOR (1 downto 0);
    col_j : IN STD_LOGIC_VECTOR (1 downto 0);
    A_i_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_i_V_0_ce0 : OUT STD_LOGIC;
    A_i_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_0_we0 : OUT STD_LOGIC;
    A_i_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_i_V_0_ce1 : OUT STD_LOGIC;
    A_i_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_0_we1 : OUT STD_LOGIC;
    A_i_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_i_V_1_ce0 : OUT STD_LOGIC;
    A_i_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_1_we0 : OUT STD_LOGIC;
    A_i_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_i_V_1_ce1 : OUT STD_LOGIC;
    A_i_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_i_V_1_we1 : OUT STD_LOGIC;
    A_j_V_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_j_V_0_ce0 : OUT STD_LOGIC;
    A_j_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_0_we0 : OUT STD_LOGIC;
    A_j_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_j_V_0_ce1 : OUT STD_LOGIC;
    A_j_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_0_we1 : OUT STD_LOGIC;
    A_j_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_j_V_1_ce0 : OUT STD_LOGIC;
    A_j_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_1_we0 : OUT STD_LOGIC;
    A_j_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_j_V_1_ce1 : OUT STD_LOGIC;
    A_j_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A_j_V_1_we1 : OUT STD_LOGIC;
    matA_V_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    matA_V_0_ce0 : OUT STD_LOGIC;
    matA_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matA_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    matA_V_0_we0 : OUT STD_LOGIC;
    matA_V_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    matA_V_0_ce1 : OUT STD_LOGIC;
    matA_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matA_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    matA_V_0_we1 : OUT STD_LOGIC;
    matA_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    matA_V_1_ce0 : OUT STD_LOGIC;
    matA_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matA_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    matA_V_1_we0 : OUT STD_LOGIC;
    matA_V_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    matA_V_1_ce1 : OUT STD_LOGIC;
    matA_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matA_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    matA_V_1_we1 : OUT STD_LOGIC;
    V_i_V_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_i_V_0_ce0 : OUT STD_LOGIC;
    V_i_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_0_we0 : OUT STD_LOGIC;
    V_i_V_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_i_V_0_ce1 : OUT STD_LOGIC;
    V_i_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_0_we1 : OUT STD_LOGIC;
    V_i_V_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_i_V_1_ce0 : OUT STD_LOGIC;
    V_i_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_1_we0 : OUT STD_LOGIC;
    V_i_V_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_i_V_1_ce1 : OUT STD_LOGIC;
    V_i_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_i_V_1_we1 : OUT STD_LOGIC;
    V_j_V_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_j_V_0_ce0 : OUT STD_LOGIC;
    V_j_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_0_we0 : OUT STD_LOGIC;
    V_j_V_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_j_V_0_ce1 : OUT STD_LOGIC;
    V_j_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_0_we1 : OUT STD_LOGIC;
    V_j_V_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_j_V_1_ce0 : OUT STD_LOGIC;
    V_j_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_1_we0 : OUT STD_LOGIC;
    V_j_V_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    V_j_V_1_ce1 : OUT STD_LOGIC;
    V_j_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    V_j_V_1_we1 : OUT STD_LOGIC;
    matV_V_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    matV_V_0_ce0 : OUT STD_LOGIC;
    matV_V_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matV_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    matV_V_0_we0 : OUT STD_LOGIC;
    matV_V_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    matV_V_0_ce1 : OUT STD_LOGIC;
    matV_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matV_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    matV_V_0_we1 : OUT STD_LOGIC;
    matV_V_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    matV_V_1_ce0 : OUT STD_LOGIC;
    matV_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matV_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    matV_V_1_we0 : OUT STD_LOGIC;
    matV_V_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    matV_V_1_ce1 : OUT STD_LOGIC;
    matV_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    matV_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    matV_V_1_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    n_ap_vld : IN STD_LOGIC;
    col_i_ap_vld : IN STD_LOGIC;
    col_j_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of LLSSineReconstruction_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_s is 
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_start : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_done : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_continue : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_idle : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_write : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_write : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_write : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_write : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_write : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_start : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_done : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_continue : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_idle : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_din : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_write : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_din : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_write : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_din : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_write : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_i_read : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_j_read : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_ce1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_we1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_ce1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_we1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_ce1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_we1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_ce1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_we1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce0 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce1 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce0 : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce1 : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_start : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_done : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_continue : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_idle : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_n_read : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_i_read : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_j_read : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_ce1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_we1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_ce1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_we1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_ce1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_we1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_address1 : STD_LOGIC_VECTOR (0 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_ce1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_we1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce0 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce1 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce0 : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce1 : STD_LOGIC;
    signal n_c_full_n : STD_LOGIC;
    signal n_c_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal n_c_empty_n : STD_LOGIC;
    signal col_i_c_full_n : STD_LOGIC;
    signal col_i_c_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal col_i_c_empty_n : STD_LOGIC;
    signal col_i_c9_full_n : STD_LOGIC;
    signal col_i_c9_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal col_i_c9_empty_n : STD_LOGIC;
    signal col_j_c_full_n : STD_LOGIC;
    signal col_j_c_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal col_j_c_empty_n : STD_LOGIC;
    signal col_j_c10_full_n : STD_LOGIC;
    signal col_j_c10_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal col_j_c10_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_start_full_n : STD_LOGIC;
    signal read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_start_write : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_start_full_n : STD_LOGIC;
    signal read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_start_write : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_start_full_n : STD_LOGIC;
    signal read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_start_write : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component LLSSineReconstruction_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        n : IN STD_LOGIC_VECTOR (1 downto 0);
        col_i : IN STD_LOGIC_VECTOR (1 downto 0);
        col_j : IN STD_LOGIC_VECTOR (1 downto 0);
        n_out_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        n_out_full_n : IN STD_LOGIC;
        n_out_write : OUT STD_LOGIC;
        col_i_out_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        col_i_out_full_n : IN STD_LOGIC;
        col_i_out_write : OUT STD_LOGIC;
        col_i_out1_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        col_i_out1_full_n : IN STD_LOGIC;
        col_i_out1_write : OUT STD_LOGIC;
        col_j_out_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        col_j_out_full_n : IN STD_LOGIC;
        col_j_out_write : OUT STD_LOGIC;
        col_j_out2_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        col_j_out2_full_n : IN STD_LOGIC;
        col_j_out2_write : OUT STD_LOGIC );
    end component;


    component LLSSineReconstruction_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        alpha_strm1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        alpha_strm1_full_n : IN STD_LOGIC;
        alpha_strm1_write : OUT STD_LOGIC;
        beta_strm2_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        beta_strm2_full_n : IN STD_LOGIC;
        beta_strm2_write : OUT STD_LOGIC;
        gamma_strm3_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        gamma_strm3_full_n : IN STD_LOGIC;
        gamma_strm3_write : OUT STD_LOGIC;
        col_i_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        col_i_empty_n : IN STD_LOGIC;
        col_i_read : OUT STD_LOGIC;
        col_j_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        col_j_empty_n : IN STD_LOGIC;
        col_j_read : OUT STD_LOGIC;
        A_i_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        A_i_V_0_ce1 : OUT STD_LOGIC;
        A_i_V_0_we1 : OUT STD_LOGIC;
        A_i_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_i_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        A_i_V_1_ce1 : OUT STD_LOGIC;
        A_i_V_1_we1 : OUT STD_LOGIC;
        A_i_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_j_V_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        A_j_V_0_ce1 : OUT STD_LOGIC;
        A_j_V_0_we1 : OUT STD_LOGIC;
        A_j_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_j_V_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        A_j_V_1_ce1 : OUT STD_LOGIC;
        A_j_V_1_we1 : OUT STD_LOGIC;
        A_j_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        matA_V_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        matA_V_0_ce0 : OUT STD_LOGIC;
        matA_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        matA_V_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        matA_V_0_ce1 : OUT STD_LOGIC;
        matA_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        matA_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        matA_V_1_ce0 : OUT STD_LOGIC;
        matA_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        matA_V_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        matA_V_1_ce1 : OUT STD_LOGIC;
        matA_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component LLSSineReconstruction_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        n_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        n_empty_n : IN STD_LOGIC;
        n_read : OUT STD_LOGIC;
        col_i_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        col_i_empty_n : IN STD_LOGIC;
        col_i_read : OUT STD_LOGIC;
        col_j_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        col_j_empty_n : IN STD_LOGIC;
        col_j_read : OUT STD_LOGIC;
        V_i_V_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        V_i_V_0_ce1 : OUT STD_LOGIC;
        V_i_V_0_we1 : OUT STD_LOGIC;
        V_i_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        V_i_V_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        V_i_V_1_ce1 : OUT STD_LOGIC;
        V_i_V_1_we1 : OUT STD_LOGIC;
        V_i_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        V_j_V_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        V_j_V_0_ce1 : OUT STD_LOGIC;
        V_j_V_0_we1 : OUT STD_LOGIC;
        V_j_V_0_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        V_j_V_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        V_j_V_1_ce1 : OUT STD_LOGIC;
        V_j_V_1_we1 : OUT STD_LOGIC;
        V_j_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        matV_V_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        matV_V_0_ce0 : OUT STD_LOGIC;
        matV_V_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        matV_V_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        matV_V_0_ce1 : OUT STD_LOGIC;
        matV_V_0_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        matV_V_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        matV_V_1_ce0 : OUT STD_LOGIC;
        matV_V_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        matV_V_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        matV_V_1_ce1 : OUT STD_LOGIC;
        matV_V_1_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component LLSSineReconstruction_fifo_w2_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (1 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0 : component LLSSineReconstruction_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_start,
        ap_done => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_done,
        ap_continue => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_continue,
        ap_idle => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_idle,
        ap_ready => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready,
        n => n,
        col_i => col_i,
        col_j => col_j,
        n_out_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_din,
        n_out_full_n => n_c_full_n,
        n_out_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_write,
        col_i_out_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_din,
        col_i_out_full_n => col_i_c_full_n,
        col_i_out_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_write,
        col_i_out1_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_din,
        col_i_out1_full_n => col_i_c9_full_n,
        col_i_out1_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_write,
        col_j_out_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_din,
        col_j_out_full_n => col_j_c_full_n,
        col_j_out_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_write,
        col_j_out2_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_din,
        col_j_out2_full_n => col_j_c10_full_n,
        col_j_out2_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_write);

    read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0 : component LLSSineReconstruction_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_start,
        ap_done => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_done,
        ap_continue => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_continue,
        ap_idle => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_idle,
        ap_ready => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready,
        alpha_strm1_din => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_din,
        alpha_strm1_full_n => alpha_strm1_full_n,
        alpha_strm1_write => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_write,
        beta_strm2_din => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_din,
        beta_strm2_full_n => beta_strm2_full_n,
        beta_strm2_write => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_write,
        gamma_strm3_din => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_din,
        gamma_strm3_full_n => gamma_strm3_full_n,
        gamma_strm3_write => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_write,
        col_i_dout => col_i_c_dout,
        col_i_empty_n => col_i_c_empty_n,
        col_i_read => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_i_read,
        col_j_dout => col_j_c_dout,
        col_j_empty_n => col_j_c_empty_n,
        col_j_read => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_j_read,
        A_i_V_0_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_address1,
        A_i_V_0_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_ce1,
        A_i_V_0_we1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_we1,
        A_i_V_0_d1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_d1,
        A_i_V_1_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_address1,
        A_i_V_1_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_ce1,
        A_i_V_1_we1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_we1,
        A_i_V_1_d1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_d1,
        A_j_V_0_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_address1,
        A_j_V_0_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_ce1,
        A_j_V_0_we1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_we1,
        A_j_V_0_d1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_d1,
        A_j_V_1_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_address1,
        A_j_V_1_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_ce1,
        A_j_V_1_we1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_we1,
        A_j_V_1_d1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_d1,
        matA_V_0_address0 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address0,
        matA_V_0_ce0 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce0,
        matA_V_0_q0 => matA_V_0_q0,
        matA_V_0_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address1,
        matA_V_0_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce1,
        matA_V_0_q1 => matA_V_0_q1,
        matA_V_1_address0 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address0,
        matA_V_1_ce0 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce0,
        matA_V_1_q0 => matA_V_1_q0,
        matA_V_1_address1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address1,
        matA_V_1_ce1 => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce1,
        matA_V_1_q1 => matA_V_1_q1);

    read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0 : component LLSSineReconstruction_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_start,
        ap_done => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_done,
        ap_continue => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_continue,
        ap_idle => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_idle,
        ap_ready => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready,
        n_dout => n_c_dout,
        n_empty_n => n_c_empty_n,
        n_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_n_read,
        col_i_dout => col_i_c9_dout,
        col_i_empty_n => col_i_c9_empty_n,
        col_i_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_i_read,
        col_j_dout => col_j_c10_dout,
        col_j_empty_n => col_j_c10_empty_n,
        col_j_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_j_read,
        V_i_V_0_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_address1,
        V_i_V_0_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_ce1,
        V_i_V_0_we1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_we1,
        V_i_V_0_d1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_d1,
        V_i_V_1_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_address1,
        V_i_V_1_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_ce1,
        V_i_V_1_we1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_we1,
        V_i_V_1_d1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_d1,
        V_j_V_0_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_address1,
        V_j_V_0_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_ce1,
        V_j_V_0_we1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_we1,
        V_j_V_0_d1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_d1,
        V_j_V_1_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_address1,
        V_j_V_1_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_ce1,
        V_j_V_1_we1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_we1,
        V_j_V_1_d1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_d1,
        matV_V_0_address0 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address0,
        matV_V_0_ce0 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce0,
        matV_V_0_q0 => matV_V_0_q0,
        matV_V_0_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address1,
        matV_V_0_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce1,
        matV_V_0_q1 => matV_V_0_q1,
        matV_V_1_address0 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address0,
        matV_V_1_ce0 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce0,
        matV_V_1_q0 => matV_V_1_q0,
        matV_V_1_address1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address1,
        matV_V_1_ce1 => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce1,
        matV_V_1_q1 => matV_V_1_q1);

    n_c_U : component LLSSineReconstruction_fifo_w2_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_din,
        if_full_n => n_c_full_n,
        if_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_n_out_write,
        if_dout => n_c_dout,
        if_empty_n => n_c_empty_n,
        if_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_n_read);

    col_i_c_U : component LLSSineReconstruction_fifo_w2_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_din,
        if_full_n => col_i_c_full_n,
        if_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out_write,
        if_dout => col_i_c_dout,
        if_empty_n => col_i_c_empty_n,
        if_read => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_i_read);

    col_i_c9_U : component LLSSineReconstruction_fifo_w2_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_din,
        if_full_n => col_i_c9_full_n,
        if_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_i_out1_write,
        if_dout => col_i_c9_dout,
        if_empty_n => col_i_c9_empty_n,
        if_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_i_read);

    col_j_c_U : component LLSSineReconstruction_fifo_w2_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_din,
        if_full_n => col_j_c_full_n,
        if_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out_write,
        if_dout => col_j_c_dout,
        if_empty_n => col_j_c_empty_n,
        if_read => read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_col_j_read);

    col_j_c10_U : component LLSSineReconstruction_fifo_w2_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_din,
        if_full_n => col_j_c10_full_n,
        if_write => read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_col_j_out2_write,
        if_dout => col_j_c10_dout,
        if_empty_n => col_j_c10_empty_n,
        if_read => read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_col_j_read);





    ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready <= ap_sync_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready <= ap_sync_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready <= ap_sync_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    A_i_V_0_address0 <= ap_const_lv7_0;
    A_i_V_0_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_address1;
    A_i_V_0_ce0 <= ap_const_logic_0;
    A_i_V_0_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_ce1;
    A_i_V_0_d0 <= ap_const_lv64_0;
    A_i_V_0_d1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_d1;
    A_i_V_0_we0 <= ap_const_logic_0;
    A_i_V_0_we1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_0_we1;
    A_i_V_1_address0 <= ap_const_lv7_0;
    A_i_V_1_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_address1;
    A_i_V_1_ce0 <= ap_const_logic_0;
    A_i_V_1_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_ce1;
    A_i_V_1_d0 <= ap_const_lv64_0;
    A_i_V_1_d1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_d1;
    A_i_V_1_we0 <= ap_const_logic_0;
    A_i_V_1_we1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_i_V_1_we1;
    A_j_V_0_address0 <= ap_const_lv7_0;
    A_j_V_0_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_address1;
    A_j_V_0_ce0 <= ap_const_logic_0;
    A_j_V_0_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_ce1;
    A_j_V_0_d0 <= ap_const_lv64_0;
    A_j_V_0_d1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_d1;
    A_j_V_0_we0 <= ap_const_logic_0;
    A_j_V_0_we1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_0_we1;
    A_j_V_1_address0 <= ap_const_lv7_0;
    A_j_V_1_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_address1;
    A_j_V_1_ce0 <= ap_const_logic_0;
    A_j_V_1_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_ce1;
    A_j_V_1_d0 <= ap_const_lv64_0;
    A_j_V_1_d1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_d1;
    A_j_V_1_we0 <= ap_const_logic_0;
    A_j_V_1_we1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_A_j_V_1_we1;
    V_i_V_0_address0 <= ap_const_lv1_0;
    V_i_V_0_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_address1;
    V_i_V_0_ce0 <= ap_const_logic_0;
    V_i_V_0_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_ce1;
    V_i_V_0_d0 <= ap_const_lv64_0;
    V_i_V_0_d1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_d1;
    V_i_V_0_we0 <= ap_const_logic_0;
    V_i_V_0_we1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_0_we1;
    V_i_V_1_address0 <= ap_const_lv1_0;
    V_i_V_1_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_address1;
    V_i_V_1_ce0 <= ap_const_logic_0;
    V_i_V_1_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_ce1;
    V_i_V_1_d0 <= ap_const_lv64_0;
    V_i_V_1_d1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_d1;
    V_i_V_1_we0 <= ap_const_logic_0;
    V_i_V_1_we1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_i_V_1_we1;
    V_j_V_0_address0 <= ap_const_lv1_0;
    V_j_V_0_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_address1;
    V_j_V_0_ce0 <= ap_const_logic_0;
    V_j_V_0_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_ce1;
    V_j_V_0_d0 <= ap_const_lv64_0;
    V_j_V_0_d1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_d1;
    V_j_V_0_we0 <= ap_const_logic_0;
    V_j_V_0_we1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_0_we1;
    V_j_V_1_address0 <= ap_const_lv1_0;
    V_j_V_1_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_address1;
    V_j_V_1_ce0 <= ap_const_logic_0;
    V_j_V_1_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_ce1;
    V_j_V_1_d0 <= ap_const_lv64_0;
    V_j_V_1_d1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_d1;
    V_j_V_1_we0 <= ap_const_logic_0;
    V_j_V_1_we1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_V_j_V_1_we1;
    alpha_strm1_din <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_din;
    alpha_strm1_write <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_alpha_strm1_write;
    ap_done <= ap_sync_done;
    ap_idle <= (read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_idle and read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_idle and read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_done and read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_done);
    ap_sync_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready <= (read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready or ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready);
    ap_sync_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready <= (read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready or ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready);
    ap_sync_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready <= (read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready or ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready);
    ap_sync_ready <= (ap_sync_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready and ap_sync_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready and ap_sync_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready);
    beta_strm2_din <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_din;
    beta_strm2_write <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_beta_strm2_write;
    gamma_strm3_din <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_din;
    gamma_strm3_write <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_gamma_strm3_write;
    matA_V_0_address0 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address0;
    matA_V_0_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_address1;
    matA_V_0_ce0 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce0;
    matA_V_0_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_0_ce1;
    matA_V_0_d0 <= ap_const_lv64_0;
    matA_V_0_d1 <= ap_const_lv64_0;
    matA_V_0_we0 <= ap_const_logic_0;
    matA_V_0_we1 <= ap_const_logic_0;
    matA_V_1_address0 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address0;
    matA_V_1_address1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_address1;
    matA_V_1_ce0 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce0;
    matA_V_1_ce1 <= read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_matA_V_1_ce1;
    matA_V_1_d0 <= ap_const_lv64_0;
    matA_V_1_d1 <= ap_const_lv64_0;
    matA_V_1_we0 <= ap_const_logic_0;
    matA_V_1_we1 <= ap_const_logic_0;
    matV_V_0_address0 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address0;
    matV_V_0_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_address1;
    matV_V_0_ce0 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce0;
    matV_V_0_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_0_ce1;
    matV_V_0_d0 <= ap_const_lv64_0;
    matV_V_0_d1 <= ap_const_lv64_0;
    matV_V_0_we0 <= ap_const_logic_0;
    matV_V_0_we1 <= ap_const_logic_0;
    matV_V_1_address0 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address0;
    matV_V_1_address1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_address1;
    matV_V_1_ce0 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce0;
    matV_V_1_ce1 <= read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_matV_V_1_ce1;
    matV_V_1_d0 <= ap_const_lv64_0;
    matV_V_1_d1 <= ap_const_lv64_0;
    matV_V_1_we0 <= ap_const_logic_0;
    matV_V_1_we1 <= ap_const_logic_0;
    read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_continue <= ap_sync_continue;
    read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_start <= ((ap_sync_reg_read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_start_full_n <= ap_const_logic_1;
    read_V_2cols_ap_fixed_64_21_0_3_0_3_2_2_U0_start_write <= ap_const_logic_0;
    read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_continue <= ap_sync_continue;
    read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_start <= ((ap_sync_reg_read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_start_full_n <= ap_const_logic_1;
    read_and_gen_2x2_ap_fixed_64_21_0_3_0_160_3_2_80_U0_start_write <= ap_const_logic_0;
    read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_continue <= ap_const_logic_1;
    read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_start <= ((ap_sync_reg_read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_start_full_n <= ap_const_logic_1;
    read_to_2cols_ap_fixed_64_21_0_3_0_160_3_2_80_2_2_entry57_U0_start_write <= ap_const_logic_0;
end behav;
